name = "trig-egg"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TrigEgg"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "egg"
git  = "https://github.com/marcusrossel/lean-egg"
rev  = "main"

[[lean_lib]]
name = "TrigEgg"
